### ISSUE TITLE
Criação do banco de dados

### ISSUE THREAD

**Issue by MagnusIIIBR** [MagnusIIIBR/ProjetoFaculdade#6]
Criação do banco de dados em MySQL e seu script para que possa ser compartilhado com os demais participantes do projeto.

**Comment by marcobrandaodf** [comment]
USE `master`
;
/*****\* Object:  Database `Projeto`    Script Date: 09/03/2016 20:07:50 *****_/
CREATE DATABASE `Projeto`
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Projeto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Projeto.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Projeto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Projeto_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
;
ALTER DATABASE `Projeto`  COMPATIBILITY_LEVEL = 120
;
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC `Projeto`.`sp_fulltext_database` @action = 'enable'
end 
;
ALTER DATABASE `Projeto`  ANSI_NULL_DEFAULT OFF 
;
ALTER DATABASE `Projeto` 
ALTER DATABASE `Projeto` 
ALTER DATABASE `Projeto`  ANSI_WARNINGS OFF 
;
ALTER DATABASE `Projeto`  ARITHABORT OFF 
;
ALTER DATABASE `Projeto`  AUTO_CLOSE OFF 
;
ALTER DATABASE `Projeto`  AUTO_SHRINK OFF 
;
ALTER DATABASE `Projeto`  AUTO_UPDATE_STATISTICS ON 
;
ALTER DATABASE `Projeto`  CURSOR_CLOSE_ON_COMMIT OFF 
;
ALTER DATABASE `Projeto`  CURSOR_DEFAULT  GLOBAL 
;
ALTER DATABASE `Projeto`  CONCAT_NULL_YIELDS_NULL OFF 
;
ALTER DATABASE `Projeto`  NUMERIC_ROUNDABORT OFF 
;
ALTER DATABASE `Projeto` 
ALTER DATABASE `Projeto`  RECURSIVE_TRIGGERS OFF 
;
ALTER DATABASE `Projeto`   DISABLE_BROKER 
;
ALTER DATABASE `Projeto`  AUTO_UPDATE_STATISTICS_ASYNC OFF 
;
ALTER DATABASE `Projeto`  DATE_CORRELATION_OPTIMIZATION OFF 
;
ALTER DATABASE `Projeto`  TRUSTWORTHY OFF 
;
ALTER DATABASE `Projeto`  ALLOW_SNAPSHOT_ISOLATION OFF 
;
ALTER DATABASE `Projeto`  PARAMETERIZATION SIMPLE 
;
ALTER DATABASE `Projeto`  READ_COMMITTED_SNAPSHOT OFF 
;
ALTER DATABASE `Projeto`  HONOR_BROKER_PRIORITY OFF 
;
ALTER DATABASE `Projeto`  RECOVERY FULL 
;
ALTER DATABASE `Projeto`   MULTI_USER 
;
ALTER DATABASE `Projeto`  PAGE_VERIFY SUM  
;
ALTER DATABASE `Projeto`  DB_CHAINING OFF 
;
ALTER DATABASE `Projeto`  FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
;
ALTER DATABASE `Projeto`  TARGET_RECOVERY_TIME = 0 SECONDS 
;
ALTER DATABASE `Projeto`  DELAYED_DURABILITY = DISABLED 
;
EXEC sys.sp_db_vardecimal_storage_format N'Projeto', N'ON'
;
USE `Projeto`
;
/**_**\* Object:  Table `Car;`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Car;`(
    `IdCar;` int AUTO_INCREMENT NOT NULL,
    `NomeCar;` varchar(20) NOT NULL,
    `NivelPermissao` `tinyint` NOT NULL,
  `PK_Car;` PRIMARY KEY 
(
    `IdCar;` ASC
)
)
;
/*****\* Object:  Table `Cliente`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Cliente`(
    `IdPessoa` int AUTO_INCREMENT NOT NULL,
  `PK_Cliente` PRIMARY KEY 
(
    `IdPessoa` ASC
)
)
;
/*****\* Object:  Table `Fornecedor`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Fornecedor`(
    `IdFornecedor` int AUTO_INCREMENT NOT NULL,
  `PK_Fornecedor` PRIMARY KEY 
(
    `IdFornecedor` ASC
)
)
;
/*****\* Object:  Table `Funcionario`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Funcionario`(
    `IdPessoa` int NOT NULL,
    `IdCar;` int NOT NULL,
    `Usuario` varchar(15) NOT NULL,
    `Senha` varchar(65) NOT NULL,
  `PK_Funcionario` PRIMARY KEY 
(
    `IdPessoa` ASC
)
)
;
/*****\* Object:  Table `Genero`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Genero`(
    `IdGenero` int AUTO_INCREMENT NOT NULL,
    `Nome` varchar(50) NOT NULL,
  `PK_Genero` PRIMARY KEY 
(
    `IdGenero` ASC
)
)
;
/*****\* Object:  Table `Marca`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Marca`(
    `IdMarca` int AUTO_INCREMENT NOT NULL,
    `Nome` varchar(30) NOT NULL,
  `PK_Marca` PRIMARY KEY 
(
    `IdMarca` ASC
)
)
;
/*****\* Object:  Table `Pessoa`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Pessoa`(
    `IdPessoa` int NOT NULL,
    `IdTelefone` int AUTO_INCREMENT NOT NULL,
    `IdEstado` int NOT NULL,
    `Endereco` varchar(200) NULL,
    `Numero` varchar(20) NULL,
    `Bairro` varchar(50) NULL,
    `Cidade` varchar(30) NULL,
    `Email` varchar(40) NULL,
  `PK_Pessoa` PRIMARY KEY 
(
    `IdPessoa` ASC
)
)
;
/*****\* Object:  Table `PessoaFisica`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `PessoaFisica`(
    `IdPessoa` int NOT NULL,
    `CPF` varchar(20) NOT NULL,
    `RG` varchar(20) NOT NULL,
  `PK_PessoaFisica` PRIMARY KEY 
(
    `IdPessoa` ASC
)
)
;
/*****\* Object:  Table `PessoaJuridica`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `PessoaJuridica`(
    `IdPessoa` int AUTO_INCREMENT NOT NULL,
    `CNPJ` varchar(20) NOT NULL,
    `NomeFantasia` varchar(50) NOT NULL,
  `PK_PessoaJuridica` PRIMARY KEY 
(
    `IdPessoa` ASC
)
)
;
/*****\* Object:  Table `Produto`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Produto`(
    `IdProduto` int AUTO_INCREMENT NOT NULL,
    `IdMarca` int NOT NULL,
    `IdTipoCalcado` int NOT NULL,
    `IdGenero` int NOT NULL,
    `IdFornecedor` int NOT NULL,
    `Preco` decimal(7, 2) NOT NULL,
    `Tamanho` `tinyint` NOT NULL,
  `PK_Produto` PRIMARY KEY 
(
    `IdProduto` ASC
)
)
;
/*****\* Object:  Table `Telefone`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Telefone`(
    `IdTelefone` int AUTO_INCREMENT NOT NULL,
    `IdTipoTelefone` int NOT NULL,
    `IdPessoa` int NOT NULL,
    `NumeroTelefone` varchar(15) NOT NULL,
  `PK_Telefone` PRIMARY KEY 
(
    `IdTelefone` ASC
)
)
;
/*****\* Object:  Table `TipoCalcado`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `TipoCalcado`(
    `IdTipoCalcado` int AUTO_INCREMENT NOT NULL,
    `Nome` varchar(2) NOT NULL,
  `PK_TipoCalcado` PRIMARY KEY 
(
    `IdTipoCalcado` ASC
)
)
;
/*****\* Object:  Table `TipoTelefone`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `TipoTelefone`(
    `IdTipoTelefone` int AUTO_INCREMENT NOT NULL,
    `Nome` varchar(15) NOT NULL,
  `PK_TipoTelefone` PRIMARY KEY 
(
    `IdTipoTelefone` ASC
)
)
;
/*****\* Object:  Table `Venda`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `Venda`(
    `IdVenda` int NOT NULL,
    `IdFuncionario` int NOT NULL,
    `IdCliente` int NOT NULL,
    `DataVenda` `date` NOT NULL,
  `PK_Venda` PRIMARY KEY 
(
    `IdVenda` ASC
)
)
;
/*****\* Object:  Table `VendaProduto`    Script Date: 09/03/2016 20:07:50 ******/

CREATE TABLE `VendaProduto`(
    `IdVendaProduto` int NOT NULL,
    `IdVenda` int NOT NULL,
    `IdProduto` int NOT NULL,
    `ValorProduto` numeric(8, 2) NOT NULL,
    `QuantidadeProduto` int NOT NULL,
  `PK_VendaProduto` PRIMARY KEY 
(
    `IdVendaProduto` ASC
)
)
;
ALTER TABLE `Cliente`    ADD   FOREIGN KEY (`IdPessoa`)
REFERENCES `PessoaFisica` (`IdPessoa`)
;
ALTER TABLE `Cliente`   `FK_Cliente_PessoaFisica`
;
ALTER TABLE `Cliente`    ADD   FOREIGN KEY (`IdPessoa`)
REFERENCES `PessoaJuridica` (`IdPessoa`)
;
ALTER TABLE `Cliente`   `FK_Cliente_PessoaJuridica`
;
ALTER TABLE `Funcionario`    ADD   FOREIGN KEY (`IdCar;`)
REFERENCES `Car;` (`IdCar;`)
;
ALTER TABLE `Funcionario`   `FK_Funcionario_Car;`
;
ALTER TABLE `Funcionario`    ADD   FOREIGN KEY (`IdPessoa`)
REFERENCES `PessoaFisica` (`IdPessoa`)
;
ALTER TABLE `Funcionario`   `FK_Funcionario_PessoaFisica`
;
ALTER TABLE `Pessoa`    ADD   FOREIGN KEY (`IdTelefone`)
REFERENCES `Telefone` (`IdTelefone`)
;
ALTER TABLE `Pessoa`   `FK_Pessoa_Telefone`
;
ALTER TABLE `PessoaFisica`    ADD   FOREIGN KEY (`IdPessoa`)
REFERENCES `Pessoa` (`IdPessoa`)
;
ALTER TABLE `PessoaFisica`   `FK_PessoaFisica_Pessoa`
;
ALTER TABLE `PessoaJuridica`    ADD   FOREIGN KEY (`IdPessoa`)
REFERENCES `Pessoa` (`IdPessoa`)
;
ALTER TABLE `PessoaJuridica`   `FK_PessoaJuridica_Pessoa`
;
ALTER TABLE `Produto`    ADD   FOREIGN KEY (`IdFornecedor`)
REFERENCES `Fornecedor` (`IdFornecedor`)
;
ALTER TABLE `Produto`   `FK_Produto_Fornecedor`
;
ALTER TABLE `Produto`    ADD   FOREIGN KEY (`IdGenero`)
REFERENCES `Genero` (`IdGenero`)
;
ALTER TABLE `Produto`   `FK_Produto_Genero`
;
ALTER TABLE `Produto`    ADD   FOREIGN KEY (`IdMarca`)
REFERENCES `Marca` (`IdMarca`)
;
ALTER TABLE `Produto`   `FK_Produto_Marca`
;
ALTER TABLE `Produto`    ADD   FOREIGN KEY (`IdTipoCalcado`)
REFERENCES `TipoCalcado` (`IdTipoCalcado`)
;
ALTER TABLE `Produto`   `FK_Produto_TipoCalcado`
;
ALTER TABLE `Telefone`    ADD   FOREIGN KEY (`IdTipoTelefone`)
REFERENCES `TipoTelefone` (`IdTipoTelefone`)
;
ALTER TABLE `Telefone`   `FK_Telefone_TipoTelefone`
;
ALTER TABLE `Venda`    ADD   FOREIGN KEY (`IdFuncionario`)
REFERENCES `Pessoa` (`IdPessoa`)
;
ALTER TABLE `Venda`   `FK_Venda_Pessoa`
;
ALTER TABLE `Venda`    ADD   FOREIGN KEY (`IdCliente`)
REFERENCES `Pessoa` (`IdPessoa`)
;
ALTER TABLE `Venda`   `FK_Venda_Pessoa1`
;
ALTER TABLE `VendaProduto`    ADD   FOREIGN KEY (`IdProduto`)
REFERENCES `Produto` (`IdProduto`)
;
ALTER TABLE `VendaProduto`   `FK_VendaProduto_Produto`
;
ALTER TABLE `VendaProduto`    ADD   FOREIGN KEY (`IdVenda`)
REFERENCES `Venda` (`IdVenda`)
;
ALTER TABLE `VendaProduto`   `FK_VendaProduto_Venda`
;
USE `master`
;
ALTER DATABASE `Projeto`   READ_WRITE
